import { useState } from "react";
import { httpsCallable } from "firebase/functions";
import { useRouter } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { functions } from "../../lib/firebase";

const categories=[{id:"idea",label:"An idea"},{id:"problem",label:"Something got in my way"},{id:"question",label:"A question"},{id:"praise",label:"Something worked well"}] as const;
export default function FeedbackPage(){const router=useRouter();const[category,setCategory]=useState("idea");const[message,setMessage]=useState("");const[contact,setContact]=useState(true);const[busy,setBusy]=useState(false);const[result,setResult]=useState("");
 const submit=async()=>{setBusy(true);setResult("");try{await httpsCallable(functions,"submitCustomerFeedback")({category,message,contactAllowed:contact});setMessage("");setResult("Thank you. Your feedback went directly to Aaron.");}catch(error:any){setResult(error?.message||"Unable to send feedback right now.");}finally{setBusy(false);}};
 return <ScrollView keyboardShouldPersistTaps="handled" style={styles.page} contentContainerStyle={styles.content}><Pressable onPress={()=>router.replace("/(app)/settings")}><Text style={styles.back}>‹ Back to Settings</Text></Pressable><Text style={styles.eyebrow}>HELP SHAPE WE HEART PAPERWORK</Text><Text style={styles.title}>Tell me what would make this better.</Text><Text style={styles.intro}>Customer feedback is one of our pillars. I want to know what is confusing, what gets in your way, what is missing, and what already works. Your feedback goes directly to Aaron and is never published as a review.</Text>
 <Text style={styles.label}>What kind of feedback is this?</Text><View style={styles.choices}>{categories.map(item=><Pressable key={item.id} onPress={()=>setCategory(item.id)} style={[styles.choice,category===item.id&&styles.choiceOn]}><Text style={[styles.choiceText,category===item.id&&styles.choiceTextOn]}>{item.label}</Text></Pressable>)}</View>
 <Text style={styles.label}>What should I know?</Text><TextInput multiline maxLength={2000} value={message} onChangeText={setMessage} placeholder="Tell me what happened or what you would like to see…" style={[styles.input,styles.textarea]}/>
 <Pressable onPress={()=>setContact(!contact)} style={styles.checkRow}><Text style={styles.box}>{contact?"✓":""}</Text><Text style={styles.checkText}>Aaron may contact me at my account email to better understand this feedback.</Text></Pressable>
 <Pressable disabled={busy||message.trim().length<10} onPress={()=>void submit()} style={[styles.submit,(busy||message.trim().length<10)&&styles.disabled]}><Text style={styles.submitText}>{busy?"Sending…":"Send feedback to Aaron"}</Text></Pressable>{!!result&&<Text style={styles.result}>{result}</Text>}</ScrollView>}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:"#F6F5F1"},content:{width:"100%",maxWidth:720,alignSelf:"center",padding:24,paddingBottom:72},back:{color:"#27500A",fontWeight:"800",marginBottom:30},eyebrow:{color:"#3B6D11",fontSize:12,fontWeight:"800",letterSpacing:1.1},title:{color:"#1A1915",fontSize:36,lineHeight:43,fontWeight:"800",marginTop:8},intro:{color:"#5F5D57",fontSize:15,lineHeight:24,marginTop:14},label:{color:"#1A1915",fontSize:14,fontWeight:"800",marginTop:24,marginBottom:9},choices:{flexDirection:"row",flexWrap:"wrap",gap:8},choice:{borderWidth:1,borderColor:"#CFCBC0",borderRadius:9,paddingHorizontal:13,paddingVertical:10,backgroundColor:"#FFF"},choiceOn:{backgroundColor:"#27500A",borderColor:"#27500A"},choiceText:{color:"#45433F",fontWeight:"700"},choiceTextOn:{color:"#FFF"},input:{backgroundColor:"#FFF",borderWidth:1,borderColor:"#CFCBC0",borderRadius:10,padding:14,fontSize:15,color:"#1A1915"},textarea:{minHeight:170,textAlignVertical:"top"},checkRow:{flexDirection:"row",alignItems:"flex-start",gap:10,marginTop:18},box:{width:22,height:22,borderWidth:1,borderColor:"#8A8880",borderRadius:4,textAlign:"center",fontWeight:"800",color:"#27500A"},checkText:{flex:1,color:"#5F5D57",fontSize:14,lineHeight:21},submit:{alignSelf:"flex-start",marginTop:25,minHeight:48,paddingHorizontal:20,borderRadius:10,alignItems:"center",justifyContent:"center",backgroundColor:"#27500A"},disabled:{opacity:.45},submitText:{color:"#FFF",fontWeight:"800"},result:{marginTop:18,color:"#27500A",fontWeight:"700",lineHeight:21}});
