import { useEffect, useState } from "react";
import { onAuthStateChanged, type User } from "firebase/auth";
import { httpsCallable } from "firebase/functions";
import { Link } from "expo-router";
import Head from "expo-router/head";
import { ActivityIndicator, Platform, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import PublicFooter from "../components/public/PublicFooter";
import PublicHeader from "../components/public/PublicHeader";
import { auth, functions } from "../lib/firebase";

export default function LeaveReviewPage() {
  const [user,setUser]=useState<User|null>(auth.currentUser); const [authLoaded,setAuthLoaded]=useState(false); const [rating,setRating]=useState(0); const [reviewText,setReviewText]=useState(""); const [name,setName]=useState(""); const [title,setTitle]=useState(""); const [showCompany,setShowCompany]=useState(false); const [consent,setConsent]=useState(false); const [incentive,setIncentive]=useState(false); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  useEffect(()=>onAuthStateChanged(auth,nextUser=>{setUser(nextUser);setAuthLoaded(true);}),[]);
  const submit=async()=>{ setBusy(true); setMessage(""); try { await httpsCallable(functions,"submitCustomerReview")({rating,reviewText,reviewerName:name,reviewerTitle:title,displayCompanyName:showCompany,consentToPublish:consent,incentiveReceived:incentive}); setMessage("Thank you. Your review was submitted for authenticity and privacy review."); } catch(error:any){ setMessage(error?.message || "We couldn't submit your review."); } finally { setBusy(false); } };
  const nativeHeader = <SafeAreaView><View style={styles.nativeHeader}><Link href="/(app)/settings" asChild><Pressable><Text style={styles.backText}>‹ Back to Settings</Text></Pressable></Link><Text style={styles.nativeBrand}>We Heart Paperwork</Text></View></SafeAreaView>;
  return <><Head><title>Leave a Customer Review | We Heart Paperwork</title><meta name="robots" content="noindex,follow" /></Head><ScrollView keyboardShouldPersistTaps="handled" style={styles.page} contentContainerStyle={styles.content}>{Platform.OS === "web" ? <PublicHeader/> : nativeHeader}<View style={styles.card}><Text style={styles.eyebrow}>CUSTOMER FEEDBACK</Text><Text accessibilityRole="header" style={styles.title}>Leave an honest review.</Text><Text style={styles.help}>Your experience helps another trucking company decide whether this is the right kind of tool. Positive and critical reviews follow the same rules.</Text>
  {!authLoaded ? <ActivityIndicator size="large" color="#27500A" /> : !user ? <View><Text style={styles.notice}>Sign in to verify that you have used We Heart Paperwork.</Text><Link href={{pathname:"/(auth)/login",params:{returnTo:"/review"}}} asChild><Pressable style={styles.primary}><Text style={styles.primaryText}>Sign in to leave a review</Text></Pressable></Link></View> : <>
    <Text style={styles.label}>Overall rating</Text><View style={styles.rating}>{[1,2,3,4,5].map(value=><Pressable key={value} accessibilityRole="button" accessibilityLabel={`${value} stars`} onPress={()=>setRating(value)}><Text style={[styles.star,value<=rating&&styles.starOn]}>★</Text></Pressable>)}</View>
    <Text style={styles.label}>Your review</Text><TextInput multiline maxLength={1500} value={reviewText} onChangeText={setReviewText} placeholder="What did you use, and what was your experience?" style={[styles.input,styles.textarea]} />
    <Text style={styles.label}>Name to display</Text><TextInput maxLength={80} value={name} onChangeText={setName} placeholder="Your name" style={styles.input}/>
    <Text style={styles.label}>Role or title (optional)</Text><TextInput maxLength={80} value={title} onChangeText={setTitle} placeholder="Owner, safety manager, dispatcher…" style={styles.input}/>
    <Pressable onPress={()=>setShowCompany(!showCompany)} style={styles.checkRow}><Text style={styles.box}>{showCompany?"✓":""}</Text><Text style={styles.checkText}>You may display my company name from my account.</Text></Pressable>
    <Pressable onPress={()=>setIncentive(!incentive)} style={styles.checkRow}><Text style={styles.box}>{incentive?"✓":""}</Text><Text style={styles.checkText}>I received something of value for submitting this review. We will disclose this publicly.</Text></Pressable>
    <Pressable onPress={()=>setConsent(!consent)} style={styles.checkRow}><Text style={styles.box}>{consent?"✓":""}</Text><Text style={styles.checkText}>I confirm this is my honest experience and give We Heart Paperwork permission to publish it as written with the selected identity details.</Text></Pressable>
    <Pressable disabled={busy||rating===0||reviewText.trim().length<30||name.trim().length<2||!consent} onPress={submit} style={[styles.primary,(busy||rating===0||reviewText.trim().length<30||name.trim().length<2||!consent)&&styles.disabled]}><Text style={styles.primaryText}>{busy?"Submitting…":"Submit my review"}</Text></Pressable>
    {!!message&&<Text style={styles.message}>{message}</Text>}<Text style={styles.fine}>We may decline content that is unverifiable, contains private information, is abusive, or is unrelated. We do not rewrite reviews or reject them because of their rating. Contact support to withdraw a published review.</Text>
  </>}</View>{Platform.OS === "web" && <PublicFooter/>}</ScrollView></>;
}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:"#FAFAF8"},content:{minHeight:"100%"},nativeHeader:{minHeight:58,paddingHorizontal:18,flexDirection:"row",alignItems:"center",justifyContent:"space-between",borderBottomWidth:1,borderBottomColor:"#E5E3DA"},backText:{color:"#27500A",fontSize:14,fontWeight:"800"},nativeBrand:{color:"#1A1915",fontSize:14,fontWeight:"800"},card:{width:"100%",maxWidth:720,alignSelf:"center",paddingHorizontal:24,paddingTop:Platform.OS === "web"?64:32,paddingBottom:72},eyebrow:{color:"#3B6D11",fontSize:12,fontWeight:"800",letterSpacing:1.1,marginBottom:14},title:{color:"#1A1915",fontSize:Platform.OS === "web"?46:34,lineHeight:Platform.OS === "web"?52:40,fontWeight:"800",letterSpacing:-1.7,marginBottom:16},help:{color:"#5F5D57",fontSize:16,lineHeight:26,marginBottom:28},notice:{color:"#5F5D57",fontSize:16,lineHeight:24,marginBottom:18},label:{color:"#1A1915",fontSize:14,fontWeight:"800",marginTop:18,marginBottom:8},rating:{flexDirection:"row",gap:7},star:{fontSize:34,color:"#CBC7BB"},starOn:{color:"#B36B00"},input:{backgroundColor:"#FFF",borderWidth:1,borderColor:"#CFCBC0",borderRadius:10,paddingHorizontal:14,paddingVertical:12,fontSize:15,color:"#1A1915"},textarea:{minHeight:140,textAlignVertical:"top"},checkRow:{flexDirection:"row",alignItems:"flex-start",gap:10,marginTop:18},box:{width:22,height:22,borderWidth:1,borderColor:"#8A8880",borderRadius:4,textAlign:"center",fontWeight:"800",color:"#27500A"},checkText:{flex:1,color:"#5F5D57",fontSize:14,lineHeight:21},primary:{alignSelf:"flex-start",marginTop:26,minHeight:48,paddingHorizontal:20,borderRadius:11,alignItems:"center",justifyContent:"center",backgroundColor:"#27500A"},disabled:{opacity:.45},primaryText:{color:"#FFF",fontSize:14,fontWeight:"800"},message:{marginTop:18,color:"#27500A",fontSize:14,fontWeight:"700",lineHeight:21},fine:{marginTop:22,color:"#706E68",fontSize:12,lineHeight:19}});
